### ISSUE TITLE
[PE-D][Tester D] Event: Feature flaw

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2113-T13-4/tp#177]
I would like to key in event without an exact time because
- there is no exact end time
- It is a general time frame, no exact start and end time

![image.png](https://raw.githubusercontent.com/tanyizhe/ped/main/files/1ba23009-cc71-4c33-a2a8-7fcc3ce60d9c.png)

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: tanyizhe/ped#1

**Comment by irving11119** [comment]
Hmmmmm this is by design though.

Thoughts? @PoobalanAatmikaLakshmi @yixuann02 @T-Wan-Lin @honglinshang

**Comment by T-Wan-Lin** [comment]
Even normal calendars have a time field. I don't think this is a bug per se.
<img width="254" alt="Screenshot 2023-04-01 at 10 58 51 AM" src="https://user-images.githubusercontent.com/88520987/229262598-cd29fb47-d82b-44ed-b433-e578db81639b.png">
