### ISSUE TITLE
[PE-D][Tester A] Date logical error

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-T13-4/tp#178]
![image.png](https://raw.githubusercontent.com/Manoj364/ped/main/files/75034ab8-e2dd-4248-ad2f-2b1bf483324b.png)

Perhaps the program can throw an exception when the start date and time is later than the end date and time

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: Manoj364/ped#1

**Comment by irving11119** [comment]
Rejected. 30/3/23 00:00 is before 30/3/23 23:59
