### ISSUE TITLE
[PE-D][Tester D] lesson type does not exist

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-T13-4/tp#185]
![image.png](https://raw.githubusercontent.com/tanyizhe/ped/main/files/994e5619-afdc-48f6-b564-3136e64ca7c6.png)
added cs1010x, tut 2/3, but it tells me that lesson type does not exist.

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: tanyizhe/ped#7

**Comment by irving11119** [comment]
## Todo

1. Update User Guide to reflect addmod constraints (e.g Need to follow exact class number - 02 in this case instead of 2)
