### ISSUE TITLE
[PE-D][Tester E] Link for tp.jar file does not work

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2113-T13-4/tp#188]
Within the user guide under point 2 of the quick start, the link for what supposed to be the latest tp.jar file just redirects user back to the same user guide page.

![image.png](https://raw.githubusercontent.com/thomasjlalba/ped/main/files/dd065afa-d0ba-49a9-b752-a63826d42bac.png)

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: thomasjlalba/ped#2

**Comment by irving11119** [comment]
## Todo

1. Update User Guide with correct links
