### ISSUE TITLE
[PE-D][Tester B] Consistency of time format

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-T13-4/tp#198]
Formatting of time for non-module and module task is inconsistent.

For example the time 11:30pm is stored as 11:30PM in non-module task while stored as 2330 in module task.

-------------
Labels: `type.FeatureFlaw` `severity.VeryLow`
original: ZhongXiangWong/ped#4

**Comment by irving11119** [comment]
This issue will be fixed when date format gets updated to new format as in #169
