### ISSUE TITLE
[PE-D][Tester D] Able to have 150 mcs

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-T13-4/tp#202]
![image.png](https://raw.githubusercontent.com/tanyizhe/ped/main/files/ae854dbf-cbce-4a2b-b29e-967428b06384.png)
Able to take 144mcs of same mod

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: tanyizhe/ped#14

**Comment by irving11119** [comment]
Same issue as #199
