### ISSUE TITLE
[Enhancement] Make it more CLI friendly by making commands as flags 

### ISSUE THREAD

**Issue by PoobalanAatmikaLakshmi** [AY2223S2-CS2113-T13-4/tp#76]
## Current Implementation

Current commands for Tasks use argument flags which do not follow traditional CLI argument conventions (e.g `/from`, `/to`, `/by`).

## Possible enhancement

Update command flags to follow normal  CLI  conventions (e.g add `-m` for modules).

**Comment by irving11119** [comment]
I think we can downgrade priority to low. Students are tech savvy and will be able to adapt based on User Guide. We can implement it if we have spare time. Inbox me if you have any disagreements.

**Comment by T-Wan-Lin** [comment]
No need to change listmod to list -m, only change /by, /from, /to to -by, -from -to
