### ISSUE TITLE
[Task] Update Developer Guide 

### ISSUE THREAD

**Issue by T-Wan-Lin** [AY2223S2-CS2113-T13-4/tp#87]
## Todo

1. Acknowledge code -> Shang's Baseline Duke
2. Acknowledge external Libraries and APIs used (e.g. GSON, NUSMods API)
3. Design and Implmentation -> not urgent
4. Product Scope -> Whoever we made Apollo for
5. User Stories -> Compile whatever we have implemented thus far
6. NFR
7. Glossary
8. Instructions for Manual Testing
9. Add appropriate UML Diagrams for important classes and objects

**Comment by PoobalanAatmikaLakshmi** [comment]
Describe the implementation of at least one enhancement you have added (or planning to add).
Expected length: 1+ page per person
Describing the design at a multiple-levels (e.g., first, describe at architecture-level, then describe at component-level) is optional. It is also acceptable to have one Design & Implementation section in which you describe the entire thing at the class- and object-level.
The description can contain things such as,
How the feature is implemented (or is going to be implemented).
Why it is implemented that way.
Alternatives considered.

**Comment by irving11119** [comment]
For UML Diagrams, let's standardise with [this](https://plantuml.com) tool.
